### ISSUE TITLE
publishImageConfig step support registry-mirror

### ISSUE THREAD

**Issue by zengzhengrong** [rancher/pipeline#66]
RT
Frequently Download timeout
rancher/plugins-docker:18.09

looklike
```
stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      mirror: 'https://xxx.mirror.aliyuncs.com'
```
